config/routes.rb
Rails.application.routes.draw do
  resources :follows
  devise_for :users
  root to: 'posts#index'

  resources :users do
    member do
      get :show
      get :account
      get :cancel
      get :accept
      post :follow
      post :unfollow
    end
    resources :stories
  end

  resources :posts do
    member do
      get :like
    end
    resources :comments
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  enum account_type: { Public: 0, Private: 1 }
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true

  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users, dependent: :destroy
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users, dependent: :destroy

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  has_one :like, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def show
      @user = User.find(params[:id])
      authorize @user
   end

   def follow
      @user = User.find(params[:id])
      if @user.Public?
         current_user.followees << @user
      else
         begin
            Request.create(sender_id: current_user.id, receiver_id: @user.id)
         rescue
            flash[:alert] = "Already Requested"
         end
      end
      redirect_back(fallback_location: user_path(@user))
   end

   def unfollow
      @user = User.find(params[:id])
      current_user.followed_users.find_by(followee_id: @user.id).destroy
      redirect_back(fallback_location: user_path(@user))
   end

   def account
      if current_user.Public?
         current_user.Private!
      elsif current_user.Private?
         current_user.Public!
      end
      redirect_to user_path(current_user), flash: {notice: "Account type changed to #{current_user.account_type}"}
   end

   def cancel
      @request = Request.find_by(sender_id: current_user.id, receiver_id: params[:id])
      if @request.destroy
         redirect_back(fallback_location: user_path(params[:id]))
      end
   end

   def accept
      @user = User.find(params[:id])
      begin
         current_user.followers << @user
         Request.find_by(sender_id: @user.id, receiver_id: current_user.id).destroy
      rescue
         flash[:alert] = "Request Already Accepted"
      end
      redirect_to root_path
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="index-custom">
   <div class="d-flex flex-row justify-content-center align-item-center mt-5">
      <div>
         <%if @user.avatar.attached? %>
            <%= image_tag @user.avatar,  style: 'height:150px; width:150px; object-fit: cover;', class:'rounded-circle' %>
         <%else%>
            <%= image_tag '/default-avatar-profile-icon-vector-social-media-user-symbol-image-default-avatar-profile-icon-vector-social-media-user-symbol-209498286.jpeg',  style: 'height:150px; width:150px; object-fit: cover;', class:'rounded-circle' %>
         <%end %>
      </div>

      <div class="ml-5 mt-4">
         <h3>
            <%= @user.username%>

            <% if @user == current_user  %>
               <%= link_to 'Edit profile', edit_user_registration_path, class:'ml-4 btn btn-sm btn-outline-dark' %>
            <% elsif Request.where(sender_id: current_user.id, receiver_id: @user.id).exists? %>
               <%= link_to 'Cancel Request', cancel_user_path(@user), class:'ml-4 btn btn-sm btn-danger text-white' %>
            <% elsif !current_user.followees.include?(@user) %>
               <%= link_to 'Follow', follow_user_path, method: "POST", class:'ml-4 btn btn-sm btn-primary text-white' %>

            <% else %>
               <%= link_to 'Unfollow', unfollow_user_path, method: "POST", class:'ml-4 btn btn-sm btn-danger text-white' %>
            <% end %>
         </h3>

         <div class='d-flex flex-row mt-3 mb-3'>
            <h6 class='mr-5'><strong><%= @user.posts.count%></strong> posts</h6>
            <h6 class='mr-5'><strong><%= @user.followers.count%></strong> Followers</h6>
            <h6 class=''><strong><%= @user.followees.count%></strong> Following</h6>
         </div>

         <h5><%= @user.name%></h5>
         <pre class='bg-light'><%= @user.bio%></pre>
         <% if @user == current_user %>
            <%= link_to 'Add story', new_user_story_path(@user), class:'btn btn-sm btn-dark text-white w-100'%>
         <% end %>

      </div>
   </div>

   <div class="mt-5">
      <div class="row">
         <%# <div class="col-lg-4 col-md-6 col-12 mb-3"> %>
         <% if @user.Public?  || current_user.followees.include?(@user) || current_user== @user%>
            <% if @user.posts.empty? %>
               <h4 class='text-secondary'>No Posts to show</h4>
            <% else %>
               <%@user.posts.each do |post| %>
                  <div class='d-flex justify-content-center align-item-center'>
                     <div class="m-2">
                     <%= link_to post_path(post) do%>
                        <%=image_tag post.images[0],  style: 'height:330px; width:330px; object-fit: cover;', class:'rounded' %>
                     <%end%>
                     </div>
                  </div>
               <%end%>
            <% end %>

         <% else %>
            <h5>This account is private</h5>
         <% end %>
         <%# </div> %>
      </div>
   </div>

</div>