config/routes.rb
Rails.application.routes.draw do
  resources :follows
  devise_for :users
  root to: 'posts#index'

  resources :users do
    member do
      get :show
      get :account
      get :cancel
      get :accept
      post :follow
      post :unfollow
    end
    resources :stories
  end

  resources :posts do
    member do
      get :like
    end
    resources :comments
  end


end

app/models/post.rb
class Post < ApplicationRecord
   belongs_to :user
   has_many :comments, dependent: :destroy
   validates :images, presence: true
   has_many_attached :images, dependent: :destroy
   has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts or /posts.json
  def create
    # @post = Post.new(post_params)
    @post = current_user.posts.create(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    @post = Post.find(params[:id])
    if Like.where(post_id: @post.id, user_id: current_user.id).exists?
      @like = Like.find_by(post_id: @post.id, user_id: current_user.id)
      @like.destroy
    else
      @like  = Like.create(post_id: @post.id, user_id: current_user.id)
    end
    redirect_back(fallback_location: :back)
    # redirect_to root_path
    # respond_to? |format| do
    #   format.html {redirect_to root_path}
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:caption, :images)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :caption %>
    <%= form.text_area :caption, size:'175x15' ,class:'form-control'%>
  </div>
  <div>
      <%= form.file_field :images%>
  </div>
  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class='d-flex justify-content-center'>
   <div class='post bg-white  p-5 mt-5'>

      <h1>Editing Post</h1>
      <%= render 'form', post: @post %>
      <%= link_to 'Back', post_path(@post), class:'btn btn-dark text-white' %>

   </div>
</div>

app/views/posts/index.html.erb
<div class='container-fluid'>



  <div class="row justify-content-center">

    <div class="col-lg-5 col-sm-12">
      <div class='mt-2 overflow-auto'>
        <%User.all.each do |user|%>
          <% if  user.stories.count > 0 %>

            <% if user == current_user||current_user.followees.include?(user) %>
              <%if user.avatar.attached? %>
                <%= link_to  user_stories_path(user) do %>
                  <%= image_tag user.avatar,  style: 'height:70px; width:70px; object-fit: cover;', class:'rounded-circle story-icon ml-2' %>
                <% end %>
              <%else%>
                <%= image_tag '/default-avatar-profile-icon-vector-social-media-user-symbol-image-default-avatar-profile-icon-vector-social-media-user-symbol-209498286.jpeg',  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle ml-2' %>
              <%end %>
            <% end %>

          <% end %>
        <%end%>
      </div>
      <% User.order('RANDOM()').all.each do |followee|%>
      <% if followee == current_user || current_user.followees.include?(followee) %>
        <% followee.posts.shuffle.each do |p| %>
            <div class="post mt-3 bg-white">

              <div class="w-100">

                <div class="u-name-div mb-1">
                  <%if p.user.avatar.attached? %>
                    <%= image_tag p.user.avatar,  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle' %>
                  <%else%>
                    <%= image_tag '/default-avatar-profile-icon-vector-social-media-user-symbol-image-default-avatar-profile-icon-vector-social-media-user-symbol-209498286.jpeg',  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle' %>
                  <%end %>
                  <%= link_to p.user.username , user_path(p.user) ,class:'text-dark font-weight-bold text-decoration-none'%>
                </div>

                <div style="height: auto" data-ride="carousel">
                  <div class='carousel-inner'>
                    <%= link_to post_path(p) do %>
                      <% p.images.each_with_index do |image, i| %>
                        <div id="myCarousel" class='carousel-item <%= ' active ' if i==0 %>'>
                          <%= image_tag image,  style: 'height:auto; width:100%;' %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                </div>

                <div class="pt-1">
                  <span><strong><%= pluralize(p.likes.count,'like')%></strong></span>
                  <span class='ml-2'><strong><%= pluralize(p.comments.count,'Comment')%></strong></span>
                  <br/>
                  <% if p.caption.present? %>
                    <span><b><%= p.user.username %></b> <%= p.caption %> </span>
                  <% end %>
                  <div>

                    <% if Like.where(user_id: current_user.id, post_id: p.id).exists? %>
                      <%= link_to 'Unlike', like_post_path(p), class:'btn btn-sm btn-danger text-white mt-1 mb-1'%>
                    <% else %>
                      <%= link_to 'Like', like_post_path(p), class:'btn btn-sm btn-primary text-white mt-1 mb-1'%>
                    <% end %>


                  </div>
                </div>

              </div>

            </div>

        <% end %>
        <% end %>
      <%end%>
    </div>


    <div class='d-flex flex-column col-lg-3 col-sm-12'>
      <div style='height: 300px' class='post bg-white mt-3 ml-5 w-100 side-div'>

          <div>
            <h5 class='mt-3 text-secondary'>Suggestions For You</h5>
            <% User.all.each do |user| %>
              <div class='m-3'>
                <%if user != current_user %>

                  <% if !current_user.followees.include?(user) %>

                    <%if user.avatar.attached? %>
                      <%= image_tag user.avatar,  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle' %>
                    <%else%>
                      <%= image_tag '/default-avatar-profile-icon-vector-social-media-user-symbol-image-default-avatar-profile-icon-vector-social-media-user-symbol-209498286.jpeg',  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle' %>
                    <%end %>
                    <%= link_to user.username , user_path(user) ,class:'text-dark font-weight-bold text-decoration-none'%>
                    <%if Request.where(sender_id: current_user.id, receiver_id: user.id).exists? %>
                      <%= link_to 'Cancel', cancel_user_path(user), class:'ml-4 btn btn-sm btn-danger text-white float-right' %>
                    <% else %>
                      <%= link_to 'Follow' , follow_user_path(user), method: "POST" ,class:'btn btn-sm btn-primary text-white float-right'%>
                    <% end %>

                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>

      </div>


      <% if Request.where(receiver_id: current_user.id).exists? %>
        <div style='height: 200px' class='post bg-white mt-3 ml-5 w-100'>
          <div>
            <h5 class='mt-3 text-secondary'>Requests</h5>
              <%User.all.each do |user|%>

                <% if Request.where(sender_id: user.id, receiver_id: current_user.id).exists? %>
                  <div class='m-3'>
                    <%if user.avatar.attached? %>
                      <%= image_tag user.avatar,  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle' %>
                    <%else%>
                      <%= image_tag '/default-avatar-profile-icon-vector-social-media-user-symbol-image-default-avatar-profile-icon-vector-social-media-user-symbol-209498286.jpeg',  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle' %>
                    <%end %>
                    <%= link_to user.username , user_path(user) ,class:'text-dark font-weight-bold text-decoration-none'%>
                    <%= link_to 'Accept' , accept_user_path(user),class:'btn btn-sm btn-warning text-dark float-right'%>
                  </div>

                <% end %>

              <%end%>
          </div>
        </div>
      <% end %>



    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class='d-flex justify-content-center'>

   <div class='bg-white post p-5 mt-5'>
      <h1>New Post</h1>
      <%= render 'form', post: @post %>
      <%= link_to 'Cancel', posts_path, class:'btn-link btn btn-danger text-white' %>
   </div>


</div>

app/views/posts/show.html.erb
<div class='mt-5 h-100 w-100'>
<%# <%= link_to 'back', :back, class:'btn btn-dark text-white btn-sm m-2' %>
  <div class='row'>

      <div class="col-md-6">

        <div class="post show-post bg-white">

          <div class="w-100">
            <div class="u-name-div mb-2">

              <%if @post.user.avatar.attached? %>
                <%= image_tag @post.user.avatar,  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle' %>
              <%else%>
                <%= image_tag '/default-avatar-profile-icon-vector-social-media-user-symbol-image-default-avatar-profile-icon-vector-social-media-user-symbol-209498286.jpeg',  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle' %>
              <%end %>
              <%= link_to @post.user.username , user_path(@post.user) ,class:'text-dark font-weight-bold text-decoration-none'%>

              <% if @post.user_id == current_user.id %>
                <%= link_to 'Delete', post_path(@post),method: :delete , class:'btn btn-sm btn-danger text-white float-right m-1' %>
                <%= link_to 'Edit', edit_post_path, class:'btn btn-sm btn-dark text-white float-right m-1' %>
              <% end %>

            </div>

            <div style="height: auto" data-ride="carousel">
              <div class='carousel-inner'>
                <% @post.images.each_with_index do |image, i| %>
                  <div id="myCarousel" class='carousel-item <%= ' active ' if i==0 %>'>
                    <%=image_tag image,  style: 'height: auto; width:100%;' %>
                  </div>
                <% end %>
              </div>
            </div>

            <div class="pt-1">
              <span><strong><%= pluralize(@post.likes.count,'like')%></strong></span>
              <br/>
              <span><b><%= @post.user.username %></b>: <%= @post.caption %> </span>
              <div>
                <% if Like.where(user_id: current_user.id, post_id: @post.id).exists? %>
                      <%= link_to 'Unlike', like_post_path(@post) ,class:'btn btn-sm btn-danger text-white mt-1 mb-1 unlike-btn'%>
                <% else %>
                      <%= link_to 'Like', like_post_path(@post) ,class:'btn btn-sm btn-primary text-white mt-1 mb-1 like-btn'%>
                <% end %>
              </div>
            </div>
          </div>
      </div>
    </div>

    <div class='post show-post-comments col-3 bg-white'>
      <h3>Comments</h3>

        <%= form_with(model: [ @post, @post.comments.build ]) do |form| %>
          <div class='d-flex flex-row'>
            <div> <%= form.text_field :content, class:'form-control'%> </div>
            <div> <%= form.submit "comment", method: :post , class:'btn btn-primary btn-sm m-1'%></div>
          </div>
        <%end%>

        <div class='mt-2 w-100'>
        <% @post.comments.each do |c| %>
          <%if !c.content.nil? %>
          <div class='border p-1 mb-2 w-100'>
            <%User.all.each do |user|%>
              <% if user.id == c.user_id %>
                <span class='d-flex flex-row'>
                  <%if user.avatar.attached? %>
                    <%= image_tag user.avatar,  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle' %>
                  <%else%>
                    <%= image_tag '/default-avatar-profile-icon-vector-social-media-user-symbol-image-default-avatar-profile-icon-vector-social-media-user-symbol-209498286.jpeg',  style: 'height:32px; width:32px; object-fit: cover;', class:'rounded-circle' %>
                  <%end %>
                  <h5 class='m-1'><%=user.username%></h5>
                </span>

              <%end%>
            <%end%>
            <p class='mt-1'><%= c.content%></p>

            <% if current_user.id == c.user_id %>
              <%= link_to "delete", [c.post, c], method: :delete, class:'text-danger' %>
            <% end %>

          </div>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>

</div>