config/routes.rb
Rails.application.routes.draw do
  resources :follows
  devise_for :users
  root to: 'posts#index'

  resources :users do
    member do
      get :show
      get :account
      get :cancel
      get :accept
      post :follow
      post :unfollow
    end
    resources :stories
  end

  resources :posts do
    member do
      get :like
    end
    resources :comments
  end


end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white border sticky-top w-100">
  <div class="container">
    <%= link_to root_path, style:'width: 10%' do %>
      <%= image_tag '/Instagram_Logo_2016.png',  width: '100%' %>
    <%end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">

        <%if user_signed_in? %>

          <%= link_to posts_path do%>
            <%= image_tag '/home.png',  style: 'height:25px; width:25px; object-fit: cover;', class:'m-2 ml-3'%>
          <%end%>
          <%= link_to new_post_path do%>
            <%= image_tag '/more.png',  style: 'height:25px; width:25px; object-fit: cover;', class:'m-2 ml-3'%>
          <%end%>

          <%= link_to user_path(current_user) do%>
            <div class:"nav-link active">
              <%if current_user.avatar.attached? %>
                  <%= image_tag current_user.avatar,  style: 'height:27px; width:27px; object-fit: cover;', class:'rounded-circle m-2 ml-3' %>
                <%else%>
                  <%= image_tag '/default-avatar-profile-icon-vector-social-media-user-symbol-image-default-avatar-profile-icon-vector-social-media-user-symbol-209498286.jpeg',  style: 'height:27px; width:27px; object-fit: cover;', class:'rounded-circle m-2 ml-3' %>
                <%end %>
            </div>
          <%end%>
          <%# <%= link_to 'Sign out',destroy_user_session_path,:method => :delete, class:"nav-link active text-danger" %>
          <%= link_to destroy_user_session_path,:method => :delete do%>
            <%= image_tag '/logout.png',  style: 'height:23px; width:23px; object-fit: cover;', class:'m-2 ml-3'%>
          <%end%>
        <%else%>
          <%= link_to 'Sign up', new_user_registration_path, class:"nav-link active" %>
        <%end%>


      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
  </head>

  <body class='bg-light'>
    <%if user_signed_in? %>
    <%= render "layouts/navbar" %>
    <%end%>
    <%if notice%>
      <div class="notice alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= notice %>
      </div>
    <%elsif alert%>
      <div class="alert alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= alert %>
      </div>
    <%end%>
    <%= yield %>
  </body>
</html>